$ANSIBLE_VAULT;1.1;AES256
34616333386363613065656131363533646234623737396434303337396631343563393639316338
6133633864656534396135363261383461303531353861350a396439633939316565363032303138
61383432333565356636396164323039613131306636363135643939376265663761363964663835
3733316639346538620a353931623661333262666162333662353233363137386632626330653961
37373265353737656537373030353239323930333766623461373763323230396162353535363962
35656533326161616339353931323136373965316161313831336331333936316462633333653637
37353465636362356336646336303339653736343638626661353635616164396266643733323263
39326538636135356161383561313261633536656333383335663038343932306363376637343530
31373264356264643936386431313832303135353539343130346333636563316165363863643830
39663561346135346664363736643836333832643532643832323530326637353139356539636439
63373430356130346661373165323236353634643531643535346230306562386666316636643033
63313733386363313432303132373736363833636333373566353736643362386137326164396463
37313464333930363934363933663336626562373363383136343830623739636630353564356533
32636132616666333035306463376330313533663665343864393336353236356434653531393338
36313435366537643939616233616566393230316130643766353236353166633963386232376435
64663565316133393239333238343661366361393264613539313962353661633438316533316265
37383037316336356366663265376432366131663063313263366663656663316662646164616434
3066393138393739636461646134343365633336636438363565
